name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    #- name: Show Working Directory # does not work on windows as we are not in a powershell
    #  run: ls -lah
    - name: tree
      run: tree
    - name: Restore dependencies
      run: dotnet restore --configfile NuGet.Config ChiaPlotStatus.sln
    - name: Build
      run: dotnet build --no-restore --configuration .\ChiaPlotStatus.sln /p:Configuration=Release /p:Platform="Any CPU"
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration .\ChiaPlotStatus.sln /p:Configuration=Release /p:Platform="Any CPU"
    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin\Release\net5.0
